<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Registration FY2020</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c8a99738-d939-49f2-81bd-01f583f5050d</testSuiteGuid>
   <testCaseLink>
      <guid>ef1f6dc5-a1a0-488c-9a60-58c417bc8c32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 0.0 - Registration</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>57dd9b7b-08f9-4d54-a16d-253bc15760f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.0 - ICRC Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a3339cf-cc2c-4481-9f3f-46b7c2af306e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08ef57ca-9b9a-4cd1-8b1e-1fcae7e6d8b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e94af8d9-641d-4c9c-832c-b061e48620e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21f90912-bf97-4b3c-a5ab-7bcae72de07b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.1 - Personal Info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ca5c25e-d10b-40df-bfaf-ab0a64c1bfc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fe723a4-f8bd-466b-a122-c92fdc87d898</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56848e98-39b3-403c-938c-909f7630bfd6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f5fe832-8651-49db-9d40-f5f3e306ada6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.2 - Academic Info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0102cb08-cca6-4b6a-b45e-b07346c49f51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f48395d-28f8-4b75-823a-d33f102a44d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8379e7a1-7bb3-4303-802c-f78f2f4de55a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b1c274e-18e6-4864-ab7b-80dad56bb718</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.3 - Research Exp</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>628165fc-778b-4783-ac6b-02d574ebfd72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e63dbd2a-5b71-4530-804b-25531a0c7e1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fe0d549-2ce9-4229-9c57-7f74a4f3938c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed9d7d7f-4991-49e5-bcb2-402488104452</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.4 - Work Exp</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cd83d384-22d3-4156-9a50-59abb5048e54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.5 - Publications and Awards</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a6e033a7-368f-4d5a-b428-fdb7794598aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.6 - File Upload</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9c656169-cda4-4611-b68a-4802cdfcfe73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.7 - References</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1abe38f5-def5-4fd0-984b-a34de234a694</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.8 - Interests Checkboxes</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
