<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Registrations Demo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ff9c7b00-a23a-40f9-ac00-e842c274cb79</testSuiteGuid>
   <testCaseLink>
      <guid>4f59cbcb-8248-4aaa-927b-aee1bf84cea9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 0.0 - Registration</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>314c162a-1e51-42d8-9e31-52306df71085</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.0 - ICRC Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a3339cf-cc2c-4481-9f3f-46b7c2af306e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08ef57ca-9b9a-4cd1-8b1e-1fcae7e6d8b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e94af8d9-641d-4c9c-832c-b061e48620e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4df0d1f1-8f61-44ac-b737-b9203c8f77c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.1 - Personal Info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ca5c25e-d10b-40df-bfaf-ab0a64c1bfc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fe723a4-f8bd-466b-a122-c92fdc87d898</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56848e98-39b3-403c-938c-909f7630bfd6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>926154a6-5f1c-4723-bc09-315f9365488d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.2 - Academic Info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0102cb08-cca6-4b6a-b45e-b07346c49f51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f48395d-28f8-4b75-823a-d33f102a44d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8379e7a1-7bb3-4303-802c-f78f2f4de55a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>502ff02f-cf8d-4ffd-824d-f63523feb720</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.3 - Research Exp</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>628165fc-778b-4783-ac6b-02d574ebfd72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e63dbd2a-5b71-4530-804b-25531a0c7e1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fe0d549-2ce9-4229-9c57-7f74a4f3938c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abbd4ff5-27d2-4a74-a8a0-99ad604b935c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.4 - Work Exp</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ee8d2f27-de13-4718-8f1b-1c2e7cf14624</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.5 - Publications and Awards</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c1ccf280-fb48-465a-ba7a-8420977020c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.7 - References</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f3c325e6-2e05-4919-8c7d-c7f18b6724d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.8 - Interests Checkboxes</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
