<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Registrations Demo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ff9c7b00-a23a-40f9-ac00-e842c274cb79</testSuiteGuid>
   <testCaseLink>
      <guid>4f59cbcb-8248-4aaa-927b-aee1bf84cea9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 0.0 - Registration</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bf70ad06-83b0-40bd-a42a-a66e9bd8de3a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataOne - ICRC Users</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>bf70ad06-83b0-40bd-a42a-a66e9bd8de3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>8225b901-bea2-4e32-8f14-e5a8536a7d90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bf70ad06-83b0-40bd-a42a-a66e9bd8de3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>c02d42b8-e3c4-4909-8fe2-da0e71e919d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bf70ad06-83b0-40bd-a42a-a66e9bd8de3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>EmailAddress</value>
         <variableId>11854f78-6ab3-4e16-a77b-0a1c218b0139</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>314c162a-1e51-42d8-9e31-52306df71085</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sami Test Cases/ICRC - Application - External -Section by Section/ICRC - External - Application - 1.0 - ICRC Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e7681c2f-3eb3-41ab-a297-bfb3b7f3a785</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataOne - ICRC Users</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e7681c2f-3eb3-41ab-a297-bfb3b7f3a785</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>4a3339cf-cc2c-4481-9f3f-46b7c2af306e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e7681c2f-3eb3-41ab-a297-bfb3b7f3a785</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>08ef57ca-9b9a-4cd1-8b1e-1fcae7e6d8b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e7681c2f-3eb3-41ab-a297-bfb3b7f3a785</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>EmailAddress</value>
         <variableId>e94af8d9-641d-4c9c-832c-b061e48620e2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
