<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tile_Application_Process</name>
   <tag></tag>
   <elementGuidId>1701a640-2750-4daa-8ac1-920d716d388a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#portfoliolist > div:nth-child(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;portfoliolist&quot;]/div[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;portfoliolist&quot;]/div[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;portfoliolist&quot;]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
