<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_AK - AlaskaAL - AlabamaAR -</name>
   <tag></tag>
   <elementGuidId>40f9567c-b5e4-4ef0-87b0-96e3417d66e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ui-id-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu ui-widget ui-widget-content ui-autocomplete ui-front</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AK - AlaskaAL - AlabamaAR - ArkansasAZ - ArizonaCA - CaliforniaCO - ColoradoCT - ConnecticutDC - District of ColumbiaDE - DelawareFL - FloridaGA - GeorgiaHI - HawaiiIA - IowaID - IdahoIL - IllinoisIN - IndianaKS - KansasKY - KentuckyLA - LouisianaMA - MassachusettsMD - MarylandME - MaineMI - MichiganMN - MinnesotaMO - MissouriMS - MississippiMT - MontanaNC - North CarolinaND - North DakotaNE - NebraskaNH - New HampshireNJ - New JerseyNM - New MexicoNV - NevadaNY - New YorkOH - OhioOK - OklahomaOR - OregonPA - PennsylvaniaRI - Rhode IslandSC - South CarolinaSD - South DakotaTN - TennesseeTX - TexasUT - UtahVA - VirginiaVT - VermontWA - WashingtonWI - WisconsinWV - West VirginiaWY - WyomingGU - GuamPR - Puerto RicoVI - U.S. Virgin Islands</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-2&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//ul[@id='ui-id-2']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//body[@id='page-home']/ul[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to login'])[1]/following::ul[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//ul[2]</value>
   </webElementXpaths>
</WebElementEntity>
